version: "3.9"
services:
  dbpost:
    image: postgres:latest
    environment:
      POSTGRES_DB: Work8
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 486820
    volumes:
      - ./data2:/var/lib/postgresql/data
      - ./init_scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5434:5432
